### ISSUE TITLE
Guys stop moving after Powered Crafting Table is spammed with bills

### ISSUE THREAD

**Issue by TheGentzy** [FluffierThanThou/RW_Manager#9] opened 2015-12-21 22:21 UTC
[output_log.txt](https://github.com/Karel-Kroeze/RW_Manager/files/69047/output_log.txt)
People who handle the Powered Crafting table stop moving and start giving 10 jobs in tick error some times after hannibal goes to manger table.
Spams recipes under Powered Crafting Table (mostly 'do 0 times' recipes and 'dismantle mechnoids 57 times' recipes)

**Comment by Karel-Kroeze** [comment] 2015-12-21 22:23
going to investigate / clean up logging

**Comment by TheGentzy** [comment] 2015-12-24 05:57
Doesn't persist thought savegames. This gonna be a tough pickle...

**Comment by FluffierThanThou** [comment] 2016-04-24 07:03
closing this as it's likely a duplicate of #4

**Closed by FluffierThanThou** 2016-04-24 07:03 UTC
Labels: bug
